name: Deploy 10S25

on:
  workflow_dispatch:

jobs:
  deploy-10s25:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: SFTP upload 10s25.fr
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: ${{ secrets._10S25_FR_SERVER }}
        username: ${{ secrets._10S25_FR_USER }}
        password: ${{ secrets._10S25_FR_PW }}
        port: 22
        uploads: |
          ./ => ${{ secrets._10S25_FR_HOME }}
        ignore-from: .github/ignore.txt

    - name: SFTP upload 10s25.ovh
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: ${{ secrets._10S25_OVH_SERVER }}
        username: ${{ secrets._10S25_OVH_USER }}
        password: ${{ secrets._10S25_OVH_PW }}
        port: 22
        uploads: |
          ./ => ${{ secrets._10S25_OVH_HOME }}
        ignore-from: .github/ignore.txt
