name: Init (OVERWRITE ALL)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        site:
          - { name: "indignonsnous.fr", prefix: "_INDIGNONSNOUS_FR" }
          - { name: "10s25.fr", prefix: "_10S25_FR" }
          - { name: "bloquonstout.ovh", prefix: "_BLOQUONSTOUT_OVH" }
          - { name: "indignonsnous.ovh", prefix: "_INDIGNONSNOUS_OVH" }
          - { name: "lesoulevementdupeuple.ovh", prefix: "_LESOULEVEMENTDUPEUPLE_OVH" }
          - { name: "marchepourladignite.ovh", prefix: "_MARCHEPOURLADIGNITE_OVH" }
          - { name: "onestla.ovh", prefix: "_ONESTLA_OVH" }
          - { name: "revoltes.ovh", prefix: "_REVOLTES_OVH" }

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          global
          local

    - name: Deploy to ${{ matrix.site.name }}
      id: deploy
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: ${{ secrets[format('{0}_SERVER', matrix.site.prefix)] }}
        username: ${{ secrets[format('{0}_USER', matrix.site.prefix)] }}
        password: ${{ secrets[format('{0}_PW', matrix.site.prefix)] }}
        port: 22
        delete: 'true'
        uploads: |
          ./ => ${{ secrets[format('{0}_HOME', matrix.site.prefix)] }}
        ignore: |
          README.md
          *.git
          */**/*git*

    - name: Report deployment status
      if: always()
      run: |
        if [ "${{ steps.deploy.outcome }}" == "success" ]; then
          echo "✅ Deployment to ${{ matrix.site.name }} succeeded"
        else
          echo "❌ Deployment to ${{ matrix.site.name }} failed"
          exit 1
        fi

  notify:
    runs-on: ubuntu-latest
    needs: deploy
    if: always()
    steps:
    - name: Send deployment summary
      run: |
        echo "Deployment Summary:"
        echo "- Total sites: 9"
        echo "- Status: ${{ needs.deploy.result }}"
        if [ "${{ needs.deploy.result }}" != "success" ]; then
          echo "⚠️ Some deployments may have failed. Check individual job logs."
        else
          echo "✅ All deployments completed successfully"
        fi





