name: Release

on:
  push:
    tags:
      - 'last'
  
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            !.github
            favicon.ico
            index.html
            README.md
            global
            local
          sparse-checkout-cone-mode: false

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: last
          name: Dernière version
          draft: false
          prerelease: false
